const messages = {
  common: {
    cashBoxActive: "Активний",
    haveQuestions: "Виникли питання?",
    faq: "Найчастіші запитання та інструкції",
    apply: "Застосувати",
    bonusGiftForbidden: "цей бонус вам недоступний",
    subscribeBot: "Підписатись на бот",
    goToTG: "Залітай за щоденними бонусами",
    chanelDG: "Канал | Dragon`s Gold",
    exit: "Вийти",
    from: "із",
    collapse: "Згорнути",
    count: "{count} раз | {count} раз | {count} рази | {count} разів",
    not: "Ні",
    next: "Далі",
    pageUpdated: "Дані цієї сторінки оновлено",
    writeToSupport: "Написати в підтримку",
    pleaseLogin: "Для можливості додавати ігри в Улюблені будь ласка увійдіть до свого облікового запису",
    ourChatBot: "Наш чат бот",
    usefulThingsAndHelp: "Корисні фішки та допомога",
    delete: "Видалити",
    cancel: "Відмінити",
    or: "або",
    socialNetworks: "Соціальні мережі",
    cashbox: "Каса",
    balance: "Баланс",
    errorServerNotResponding: "Помилка. Сервіс тимчасово недоступний",
    error: "Помилка",
    pageNotFound: "Сторінку не знайдено",
    somethingWentWrong: "Щось пішло не так",
    currentlyOffline: "ТИМЧАСОВО НЕ ПРАЦЮЄ",
    paySystemFailMessage: "Приносимо вибачення за незручності. Заваріть чашечку ароматної кави і повторіть спробу.",
    paySystemFailAvailableOption1: "Але ви можете поповнити баланс через",
    netT: "мережу термiналiв",
    paySystemNotSelected: "Не обрано платіжну систему",
    choosePaySystem: "Оберіть спосіб поповнення",
    yourAmount: "Введіть суму",
    invalidLimit: "Некоректна сума",
    minPayIn: "Мiн.: ",
    maxPayIn: "Макс.: ",
    dependsOnPaymentSystem: "залежить від обраної платіжної системи.",
    cashInTime:
      "Зазвичай кошти зараховуються на Ваш рахунок протягом 2-5 хвилин, але в рідкісних випадках це може зайняти до доби. Якщо Вам не вдалося внести депозит, будь ласка, спробуйте ще раз.",
    card: "Картка",
    kyivstar: "Київстар",
    terminals: "Термiнали",
    pay: "Поповнити",
    enterPhoneNumber: "Введіть номер телефону",
    topUpAccount: "Поповнити рахунок",
    terminalsInfo:
      "Шановний користувач, просимо уважно перевіряти дані, що Ви заповнюєте при поповненні балансу, щоб уникнути зарахування коштів помилково іншому користувачу. Портал не несе відповідальності за помилки в зазначених Вами даних при поповненні балансу через термінали.",
    manual: "Інструкція",
    your: "Ваш",
    history: "Історія",
    siteName: "Dragon`s Gold",
    withdrawal: "Виведення",
    fundsWithdrawal: "Виведення коштів",
    allRightsReserved: "Всі права захищені",
    termsSConditions: "Правила та умови",
    contractOffer: "Договір оферти",
    privacyPolicy: "Політика конфіденційності",
    responsibleGaming: "Відповідальна гра",
    refundPolicy: "Політика повернення коштів",
    aboutUs: "Про нас",
    news: "Новини",
    support: "Підтримка",
    back: "Назад",
    toHome: "На головну",
    game: "Гра",
    demo: "Демо",
    soon: "Скоро",
    onTheWay: "Вже скоро",
    license: "Ліцензія",
    licenseDescription:
      "Ліцензія на провадження діяльності з організації та проведення азартних ігор казино у мережі Інтернет від 26.04.2021, видана згідно з рішенням Комісії з регулювання азартних ігор та лотерей про видачу ліцензії №165 від 21.04.2021. Строк дії ліцензії 5 років. ТОВ «АЛЬФАГЕЙМ»",
    percentOfWin: "Загальний середній відсоток виграшу (теоретичне повернення гравцю) становить 94%-98%",
    save: "Зберегти",
    notReady: "Приносимо свої вибачення, функціонал ще в розробці",
    state: "Стан",
    date: "Дата",
    callSupport: "Для вирішення проблеми зверніться на підтримку",
    active: "Активні",
    available: "Доступні",
    archive: "Архів",
    noData: "Немає даних",
    more: "Більше",
    uploadMore: "Завантажити ще",
    send: "Відправити",
    repeatAfter: "Повторити через",
    repeatCode: "Повторити код",
    close: "Закрити",
    gameNotAvailable: "Гра недоступна",
    breakJackpot: "Зірвати джекпот",
    verification: "Верифікація",
    insuffFunds: "Недостатньо коштів",
    insuffFundsTxt: "У Вас недостатньо коштів",
    topUpToContinue: "Будь ласка, поповніть власний баланс та продовжуйте гру",
    dontHaveFavoriteGames: "У вас немає улюблених ігор, щоб додати гру в цей розділ натисніть на сердечко",
    volatilityBig: "Великий",
    volatilityOften: "Частий",
    win: "виграш",
    search: "Пошук",
    emptySearchResults: "Ігри, що відповідають заданим вимогам не знайдено. Оберіть інші параметри для пошуку.",
    popularGames: "Вас зацікавлять Популярні ігри",
    cashTitle: "Оберіть криптовалюту поповнення",
    exchange: "Поточний курс:",
    sentCurrency: "Відправляєте:",
    receivedCurrency: "Отримуєте на рахунок:",
    depositAddress: "Ваш персональний рахунок у Dragon's Gold казино.",
    depositComment: "Копіюйте, переходьте до свого крипто-кабінету, поповнюйте!",
    beCareful: "Будьте уважними!",
    depositCommentAfter: "Надсилайте тільки {0}. Надсилання будь-якої іншої монети або токена призведе до втрати ваших коштів!",
    copyAddress: "Копіювати адресу",
    wereGetCrypt: "Де взяти крипту для поповнення?",
    enableToOut: "Доступно для виведення:",
    bonusAccount: "На бонусному рахунку:",
    yourPurse: "Адреса вашого гаманця",
    sum: "Сума",
    copiedToBuffer: "Cкопійовано в буфер обміну",
    enterWallet: "Вкажіть номер гаманця",
    enterBankCard: "Вкажіть номер картки",
    enterCorrectWallet: "Вкажіть повний номер гаманця",
    enterCorrectBankCard: "Вкажіть повний номер картки",
    pleaseCheckCardNumber: "Будь ласка, перевірте коректність номера картки",
    enterTheSum: "Введіть суму, яку ви хотіли б вивести",
    payOutComment:
      "Мінімальна сума виводу складає 100 USDT. Якщо Ви бажаєте скасувати виведення грошових коштів та продовжити гру, пройдіть у вкладку",
    minSum: "Мінімальна сума виводу складає {sum} {currency}",
    maxSum: "Максимальна сума виводу складає {sum} {currency}",
    minSumPayIn: "Мінімальна сума поповнення складає {sum} {currency}",
    maxSumPayIn: "Максимальна сума поповнення складає {sum} {currency}",
    insufficientFunds: "Сума на Вашому балансі недостатня",
    wrongCard: "Номер картки може включати лише числа, перевірте правильність написання вашої карти",
    paymentProcessing: "Платіж прийнято в обробку",
    doesYHaveCrypto: "Чи є у тебе криптовалюта?",
    userWithExperience: "Так, я досвідчений користувач",
    userWithExperienceD: "У мене є криптовалюта",
    userWithNoExperience: "Немає криптовалюти, де взяти?",
    userWithNoExperienceD: "Хочу швидко та безпечно отримати криптовалюту перевіреним способом",
    choosePaymentMethod: "Оберіть спосіб поповнення.",
    paymentDescription: "Тільки перевірені сервіси та покрокові інструкції як це зробити. У Вас все вийде!",
    cryptoExchanges: "Крипто-біржі",
    exchangeBinance: {
      one: "Одна з найбільш популярних бірж в світі",
      two: "Висока швидкість проведення операцій",
      three: "Великий вибір криптовалют"
    },
    exchangeWhiteBit: {
      one: "Українська біржа",
      two: "Підтвердження особи за допомогою Дії",
      three: "Висока швидкість проведення операцій"
    },
    alternativeCrypto: "Альтернативні способи поповнення, якщо ви хочете зберегти анонімність.",
    alternativeExchanger: "Крипто-обмінник (P2P)",
    seeInstructions: "Подивися інструкції",
    downloadApp: "Використовувати додаток",
    webApp: "Перейти до веб-версії",
    chooseWay: "Обрати",
    recommendation: "Рекомендуємо",
    wayCryptoExchanges: "Оберіть спосіб для переходу до крипто-біржі",
    verifiedServices: "Тільки перевірені сервіси та покрокові інструкції як це зробити. У Вас все вийде!",
    toCashBox: "в касу",
    inputSum: "Вкажіть суму поповнення",
    inputSumRange: "Від {min} до {max}",
    depDescription: "Кошти зараховуються на ваш рахунок протягом 2-5 хвилин. Якщо ви не змогли зробити депозит, ",
    walletNumber: "Номер гаманця",
    amountWithdraw: "Сума до виведення",
    whereGetWallet: "Де взяти номер гаманця?",
    pushHere: "Тисніть сюди",
    clickHere: "тисніть тут.",
    callUs: "Зв'яжіться з нами",
    prompt: "підкажемо",
    cashPayType: "Оберіть спосіб поповнення:",
    payOutTitle: "Оберіть спосіб виводу:",
    installPWA: "Встановити додаток?",
    install: "Встановити",
    chatBotItem: {
      first: "ТВІЙ",
      second: "ПЕРСОНАЛЬНИЙ"
    },
    chatBotItemHelper: {
      first: "БОТ",
      second: "ПОМІЧНИК"
    },
    continue: "Продовжити",
    noAutoRedirect: "Якщо автоматичного переходу до платіжної системи не відбулося, натисніть на",
    noAutoRedirectLink: "посилання",
    sendRequest: "Подати заявку",
    open: "Відкрити",
    stepTwo: "Крок 2",
    payMethod: "Оберіть спосіб поповнення:",
    payMethodError: "Ви не обрали спосіб поповнення",
    policyAML: "Відмивання грошей",
    buyBonusInGame: "Купити бонус",
    buy: "Купити",
    getMagik: "Отримуй свою магічну коробку щодня!",
    today: "Сьогодні",
    tomorrow: "Завтра",
    dayOfTomorrow: "Післязавтра",
    magicBonus: "Бонусні",
    magicBonusAlready: "вже нараховані",
    availableAfterDep: "Доступні після першого депозиту!",
    user_already_has_active_bonus_exception: "У Вас вже є активний бонус",
    crTreeFs: "Бонусні фріспіни",
    crTreePercent: "Бонус на депозит",
    crTreeChoose: "Віднайди свій мільйон!",
    crTreeTomorrow: "Нові валентинки чекають Вас завтра!"
  },
  countDown: {
    days: "Днів",
    hours: "Годин",
    minutes: "Хвилин",
    seconds: "Секунд"
  },
  shortCountDown: {
    days: "Д.",
    hours: "Год.",
    minutes: "Хв.",
    seconds: "Сек."
  },
  lottery: {
    unlimitedDracoin: "Кількість елементів для розіграшу необмежена",
    coinsWager: "Відіграш",
    getCoins: "Отримано",
    untilFinish: "До завершення розіграшу",
    getForLottery: "Добуто для розіграшу",
    lotteryIsFinished: "Розіграш завершено",
    start: "Початок",
    yourDracoins: "Ваші",
    rules: "Правила розіграшу",
    payMore: "Додати +{sum} {currency} та отримати +1",
    toBalance: "В касу",
    takeOffTickets: "При виведенні коштів, з вашого рахунку будуть списані всі доступні для відіграшу | !",
    conditionToGetCoins:
      "Кожен елемент | , який Ви отримуєте, потрібно відіграти, для цього потрібно відкрутити депозит мінімум ",
    filter: {
      active: "Активні",
      finished: "Архів"
    },
    youAreNotWon: "В цей раз Ваші | не зіграли. Збирайте більше сніжинок та збільшуйте шанси в наступному розіграші!",
    waitForResult: "Зараз ми рахуємо | всіх участників розіграшу, найближчим часом буде результат!",
    collectedCoins: "зібрано",
    playingNow: "Відігрую зараз",
    playing: "Відігрую",
    coinsHaveBeenWon: "Всі | відіграно, придбати ще",
    startPlaying: "Почати відіграш, придбати | ",
    gold: "Золото дракона",
    silver: "Срібло дракона",
    snow: "Сніжинка",
    champion: "Чемпіон",
    christmas_tree: "Ялинка",
    candy: "Цукерка",
    gift: "Подарунок",
    played_gold: "Відіграно золоту монету",
    played_silver: "Відіграно срібну монету",
    played_snow: "Відіграно сніжинку",
    makeDeposit: "Роби депозит та отримуй персональний подарунок",
    availableGift: "Доступно 1 подарунок на добу"
  },
  boxes: {
    boxes: "скриню",
    filter: {
      ACTIVE: "Активні",
      COLLECTED: "Зібрані",
      ACCESSIBLE: "Доступні"
    },
    targetType: {
      SPIN_COUNT: "Виконано {count} обертів | Виконано {count} оберт | Виконано {count} оберта",
      RISK_COUNT: "Виконано {count} ризиків | Виконано {count} ризик | Виконано {count} ризика",
      // LOTTERY_ACTIVE_TICKETS_COUNT: "Зібрано {count} монет | Зібрано {count} монета | Зібрано {count} монети",
      LOTTERY_ACTIVE_TICKETS_COUNT: "Зібрано {count} елементів | Зібрано {count} елемент | Зібрано {count} елемента"
    },
    showAll: "Оглянути всі ({count})",
    current: "оберт | оберти | обертів",
    risk: "ризик | ризики | ризиків",
    // lottery: "монета | монети | монет",
    lottery: "елемент | елемента | елементів",
    maxNominal: "Макс. ставка",
    nominal: "Мін. ставка",
    winFactor: "Множ. ставки",
    finished: "Закінчиться",
    close: "Закрити",
    contents: "Вміст скрині",
    open: "Відкрити",
    playBox: "Розіграти",
    chestCollected: "Сундук зібрано, розіграти подарунок",
    pickUpLater: "Забрати пізніше",
    bonusAvailable: "Бонус вже доступний у розділі бонуси",
    readyToDraw: "Сундук зібрано, розіграти подарунок",
    congratsYourGift: "Вітаємо, Ваш подарунок",
    SPIN_COUNT: "К-сть спінів",
    RISK_COUNT: "К-сть ризиків",
    bannerText: "Наповнюй  скриню, та отримуй круті бонуси одразу або залишай на майбутнє!",
    empty_ACCESSIBLE: "Нажаль, поки “Доступних” скринь немає. ",
    empty_ACTIVE: "Нажаль, поки “Активних” скринь немає. ",
    empty_COLLECTED: "Нажаль, поки “Зібраних”скринь немає. ",
    emptyContent_ACCESSIBLE:
      "Поки можете перевірити Ваші “Активні” скрині. Продовжуйте гру, скрині обовʼязково будуть доступні незабаром.",
    emptyContent_ACTIVE: "Перевірте Ваші “Доступні” скрині, щоб наповнити їх, та отримати персональні бонуси.",
    emptyContent_COLLECTED:
      "Перевірте “Активні” скрині, продовжуйте їх наповнювати та отримуйте персональні бонуси що чекають на Вас.",
    noDep: "Бездепозитні",
    draw: "Зібрано!"
  },
  royalClub: {
    forChosen: "Для обраних",
    onlyRoyalClub: "Royal Club",
    onlyRoyalClubPlayer: "Тільки для учасників ROYAL CLUB",
    onlyRoyalClubPlayerDescription:
      "Станьте учасником ROYAL CLUB. Отримайте доступ до ROYAL SLOTS, персональних бонусів, швидких виводів та багато іншого.",
    whatIsRoyalClub: "Що таке ROYAL CLUB?",
    whatIsRoyalClubDescription:
      "Це закрита VIP спільнота, гравці, що об'єднані азартом та найбільшими перевагами! Кількість місць обмежена, будуть тільки справжні VIP гравці, тож встигніть скористатись можливістю і відчуйте всі переваги на собі!",
    whyRoyalClubSpecial: {
      title: "Чому ROYAL CLUB особливий?",
      personalManager: "Особистий менеджер",
      personalManagerDescription:
        "Ми впевнені що ніхто не буде Вас розуміти так, як наші менеджери VIP підтримки. Замовити піцу? Та легко, увійти в положення та дати особистий бонус по запиту? Легко, а може підказати в яких слотах сьогодні особливо всім щастить? ЛЕГКО!",
      closedGames: "ROYAL SLOTS",
      closedGamesDescription:
        "Відчувати себе особливим, це бути особливим, в нашому ROYAL CLUB це відчуття буде у всьому. Тільки для VIP гравців будуть доступні абсолютно нові та унікальні ROYAL SLOTS. То що, хочеться спробувати їх?",
      priorityCashOut: "Пріоритетна черга на вивід",
      priorityCashOutDescription:
        "Учасники закритого VIP клубу ROYAL CLUB перші серед перших, тож бути першому в черзі на вивід - нормальна справа!",
      personalBonuses: "ROYAL BONUS",
      personalBonusesDescription:
        "Знайома ситуація, коли полюбляєте якийсь один слот, а бонуси в ньому як наче навмисно Вас оминають? Так от, в ROYAL CLUB такого не буде, бонуси будуть відповідати ВАШОМУ бажанню, ЗАВЖДИ! А головне, бонуси на найкращих умовах!"
    },
    progressStatus: {
      beginYourWay: "Почніть свій шлях до закритої спілноти ROYAL CLUB. Ваш шлях до золота починається тут!",
      youConfident: "Ви впевнено рухаєтесь до закритої спільноти ROYAL CLUB, золото ближче ніж здається!",
      moreWayDone: "Більшість шляху вже пройдено, ROYAL CLUB ближче ніж здається!",
      dontStop: "Вже не можна зупинятися, скарби ROYAL CLUB за пів кроку від Вас!"
    },
    dontWasteTime:
      "Взагалі, описувати переваги можна ще довго, але що цікавіше, грати та вступати в закриту спільноту ROYAL CLUB самому, чи читати про неї? Не втрачайте час, подавайте заявку на вступ зараз та слідкуйте скільки залишилось до заповітного ROYAL CLUB!",
    accessDenied: "На жаль, на даний момент доступ до ROYAL CLUB для Вас закритий.",
    madeDeposits: "Зроблено депозитів (за останні {days} днів):",
    leftDeposits: "Залишилося зробити депозитів:",
    welcomeToClub: "Вітаємо в клубі для обраних",
    nowYouHaveThis: "Тепер ви маєте доступ до закритих автоматів, персональних бонусів, швидких виводів та багато іншого.",
    soonRoyal: "незабаром",
    soonOnlyRoyal: "незабаром для Royal Club",
    moneyWager: "Грошовий обіг"
  },
  bonuses: {
    needPhoneVerify: `Для активації бонуса "{bonusTitle}" необхідно верифікувати ваш номер телефону`,
    bonusesPageUpdated: "Дані по вашим бонусам оновлено",
    active: "Активні",
    available: "Доступні",
    archive: "Архів",
    getBonus: "Забрати бонус",
    buyBonus: "Купити з основного рахунку",
    buyBonusM: "Придбати бонус",
    buyBonusNoMoney: "недостатньо коштів для покупки",
    alowMoney: "Доступно на рахунку",
    getAfter: "Забрати через",
    willEnd: "Закінчиться",
    play: "Грати",
    apply: "Застосувати",
    promoCode: "Промокод",
    writePromoCode: "Введи промокод",
    codeApplied: "Промокод застосовано",
    onlyRoyalPromoCode: "Цей промокод дійсний лише для учасників ROYAL CLUB. Долучайтесь вже зараз!",
    verifyMail: "Підтвердити Email",
    verifyPhone: "Підтвердити Телефон",
    wrongPromo: "Невірний промокод",
    giftSpins: "Активовано режим безкоштовних обертів.",
    giftFinish: "Ви використали всі безкоштовні оберти.",
    giftWin: "Загальна сума виграшу",
    totalWager: "Оборот для відіграшу бонусу",
    promotionOver: "Акція закінчилася",
    emptyActive: "Ти не маєш активованих бонусів. Перевір доступні тобі бонуси.",
    availableBonuses: "Доступні бонуси",
    emptyArchive: "Поки пусто, тут буде архів твоїх бонусів",
    action: "Акція",
    finishedAction: "Завершені акції",
    currentActions: "Поточні акції",
    activationError: "Помилка активації.",
    hasActivatedBonus: "У вас вже є активований бонус. Перед активацією нового необхідно дограти поточний бонус.",
    wrongPromoCode: "Ваш промокод помилковий.",
    repeatActivatePromo: "Ви можете зв'язатися з підтримкою, або спробувати повторно активувати промокод.",
    tryOneMoreTime: "Спробувати ще",
    bonusGameIsDone: "Ви відіграли бонус! За умовами бонусу на Ваш основний рахунок було переказано {totalSum} {currency} ",
    errors: {
      user_bonus_assign_exception: "",
      bonus_by_promocode_already_used_exception: "Бонус за цим промокодом вже нараховано",
      bonus_by_promo_code_notfound_exception: "Бонус за вашим промокодом не знайдено"
    },
    getYourBonus: "Забирай свій бонус",
    chooseYourBonus: "Оберіть свій бонус",
    activeBonus: "Активний бонус, доступно {count} бонус | Активний бонус, доступно {count} бонуса |  Активний бонус, доступно {count} бонусів",
    cancelBonus: "Скасувати",
    areYouSureToCancel: "Ви впевнені, що хочете скасувати бонус?",
    deactivatePromo: "При деактивації бонусу з вашого бонусного рахунку буде списано {sum} {currency}.",
    impossibleToCancel: "Скасувати бонус неможливо, у вас є не розіграна ставка.",
    notAvailable: "Бонус недоступний",
    ifMultiAccountContactSupport:
      "Для Вашого облікового запису виявлені ознаки мультиакаунту. Бонуси заблоковані, тому що Ви використовуєте декілька акаунтів, але всі вони доступні на Вашому основному акаунті.\n" +
      "Зверніться в | службу підтримки | , якщо виникла помилка.",
    opsNoBonuses: "Ой… Бонусів поки немає",
    subscribeTgBot: "Персональний помічник в ЧАТ БОТІ повідомить про нові бонуси"
  },
  tournaments: {
    tournament: "Турнір",
    participate: "Взяти участь",
    subscribe: "Підписатися",
    subscribed: "Підписаний",
    toEnd: "До кінця",
    toStart: "До початку",
    table: "Таблиця",
    minNominal: "Мін. ставка:",
    games: "Ігри:",
    members: "Учасників:",
    moreAbout: "Детальніше",
    standingsTable: "Турнірна таблиця",
    place: "місце",
    prizePlaces: "призових місць",
    now: "Зараз",
    play: "Грати",
    prizes: "Призи",
    places: "місць",
    prizeMoney: "Призових",
    tournamentGames: "Ігри турніру",
    tournamentPrizes: "Призи турніру",
    rules: "Правила",
    upcoming: "Скоро",
    finished: "Завершені турніри",
    results: "Результати",
    takePart: "Беру участь",
    myPlace: "Місце",
    myPlaceLow: "місце",
    myPlaceModal: "Моє місце",
    awards: "Нагороди",
    isNotActive: "Турнір ще не активний",
    showMore: "Показати ще",
    hasBeenStarted: "Турнір розпочався",
    connectPersonalAgent: "Підключай персонального помічника",
    agentInfo: "Найголовніша інформація і завжди вчасно",
    gameTakePartInTournament: "Гра бере участь у турнірі",
    takePartGame: "Приєднатись",
    moreAboutGame: "Подробиці",
    iAmJoined: "Приймаю участь у турнірі",
    king: "Король турнірів",
    yourPlace: "Ваше місце"
  },
  gameVerificationModal: {
    accountIsNotVerified: "Ваш акаунт не верифікований!",
    checkDocuments: "Перевірити документи для верифікаії",
    uploadDocuments: "Завантажте документи",
    goToProfile: "Перейти до профілю",
    contactSupport: "зверніться в службу підтримки",
    playDemo: "Грати в демо режимі"
  },
  auth: {
    adultCheck: "Мені 21 рік",
    alreadyRegister: "Ви вже зареєстровані?",
    andIAgreeWith: "i я згоден з",
    and: "та",
    backToLogIn: "Авторизація",
    backToRegistration: "Назад до реєстрації",
    changePassword: "Змінити пароль",
    changePasswordSuccess: "Пароль успішно скинуто",
    checkEmail: "Пароль успішно скинуто, перевірте пошту",
    dontHaveAccountYet: "Ще немає облікового запису?",
    email: "Email",
    errorSamePasswords: "Паролі повинні співпадати",
    forgotPassword: "Забули пароль?",
    formatError: "Невірний формат",
    insertToken: "Введіть код із СМС",
    logout: "Вихід",
    newPassword: "Придумайте новий пароль",
    newPasswordInput: "Введіть новий пароль",
    password: "Пароль",
    passwordReset: "Відновлення паролю",
    phone: "Телефон",
    privacyPolicy: "Політикою конфіденційності",
    repeatPassword: "Повторіть пароль",
    restorePassword: "Відновлення паролю",
    resetPasswordByEmail: "Відправити",
    resetPasswordByPhone: "Відправити код",
    resetPasswordSuccess: "Запит на скидання паролю успішно надіслано",
    requiredField: "Обов'язкове поле",
    rules: "Правилами",
    sendAgainCode: "Повторити",
    signIn: "Вхід",
    signInError: "Помилка при вході",
    signInSuccess: "Успішний вхід",
    signUp: "Реєстрація",
    signUpError: "Помилка при реєстрації",
    signUpSuccess: "Реєстрація успішна",
    signInHeader: "Вхід",
    signUpFor10Second: "Реєстрація за 10 секунд",
    yourNumber: "Ваш номер",
    yourEmail: "Ваш Email",
    yourPassword: "Ваш пароль",
    passRules: "Пароль від 6 до 25 символів",
    registration: "Зареєструватися",
    fastStart: "Швидкий старт через",
    phoneVerifyTrouble: "Верифікація телефону",
    wrongCode: "невірний код",
    writeMail: "Введіть Email",
    putCodeFromSms: "Введіть код із SMS",
    floatingAuth: "Реєстрація та вхід",
    iHavePromoCode: "Я маю промокод",
    country: "Країна",
    currency: "Валюта",
    social: "Соц мережі",
    mobilePhone: "Мобільний телефон",
    signWith: "Увійти за допомогою",
    alertText: "Вашу країну визначено як Україну. Увага! У разі зміни країни буде змінено список способів оплати",
    currencyOptions: [
      { symbol: "₴", title: "KZT - Тенге", label: "KZT" },
      { symbol: "₴", title: "UAH - Гривня", label: "UAH" },
      { symbol: "₴", title: "EUR - Євро", label: "EUR" },
      { symbol: "₴", title: "USD - Долар", label: "USD" }
    ],
    missingInformation: "Вкажіть необхідну інформацію"
  },
  auth_errors: {
    changePasswordError: "Помилка при зміні паролю",
    resetPasswordError: "Помилка при надсиланні запиту на скидання паролю",
    formContentError: "Помилка заповнення форми",
    emailNeed: "Необхідно ввести електронну пошту",
    phoneNeed: "Необхідно ввести телефон",
    incorrectLoginOrPasswords: "Неправильний логін або пароль",
    emailOrPhoneAlreadyExists: "Ця електронна адреса або телефон вже використовуються",
    incorrectEmail: "Електронна пошта некоректна",
    incorrectPhone: "Телефон некоректний",
    insertPassword: "Необхідно ввести пароль",
    equalPasswords: "Паролі повинні співпадати",
    tokenNeed: "Необхідно ввести код",
    code_mismatch_exception: "Невірний код",
    wrong_code_exception: "Невірний код",
    phone_already_exists_exception: "Користувач з таким номером вже існує",
    email_already_exists_exception: "Користувач з такою поштою вже існує"
  },
  account: {
    bonusCondition: "+{sum} на бонусний рахунок",
    depositFS: "+{freeSpinAmount} FS за депозит!",
    minCashOut: "Мiн. сума виведення ({currency}.): ",
    maxCashOut: "Макс. сума виведення ({currency}.): ",
    transactionListEmpty: "Список транзакцiй порожнiй",
    cashOutTax: "Платіжна система може стягувати комісію.",
    cashMore: "Ваші кошти будуть виплачені в строк від 5 хвилин до 24 годин.",
    additionalInfo: "Додаткова інформація",
    additionalInfoText:
      "Виведення грошових коштів допустимо тільки на ту карту, за допомогою якої було виконано поповнення ігрового балансу. Для виведення коштів необхідно пройти верифікацію. Для цього необхідно завантажити фото паспорта, карти і Вашого обличчя з документами в розділі",
    personalInformation: "Особиста інформація",
    PDFwithDetailedInformation: "PDF з додатковою інформацією",
    additionalInfoDetails: "Докладніше",
    cashOutDelay: "Ваші кошти будуть виплачені в термін від 5 хв до 24 годин.",
    cashOutDelayDetails: "Якщо Ви бажаєте скасувати виведення коштів та продовжити гру, то перейдіть у вкладку",
    requestWithdrawal: "Вивести",
    availableToWithdrawal: "Доступно до виводу",
    inBonusGame: "У бонусної грі",
    cardNumber: "Номер картки",
    cardNumberInvalid: "Некоректний номер картки",
    moneyLimit: "Недостатньо коштів",
    minWithdrawal: "Мінімальна сума виводу",
    maxWithdrawal: "Максимальна сума виводу",
    acceptedToReview: "Запит прийнятий на обробку",
    undoWithdrawal: "Скасувати вивід",
    sumToWithdrawal: "Сума до виводу",
    sum: "Сума",
    transactionsHistory: "Історія транзакцій",
    action: "Операція",
    transactionActions: {
      CASH_IN: "Поповнення",
      CASH_OUT: "Виведення коштів",
      CASH_OUT_MANUAL: "Ручне списання",
      CASH_IN_MANUAL: "Ручне нарахування",
      BONUS_CANCELED: "Списання бонусних коштів",
      DEPOSIT_IN: "Поповнення рахунку",
      BONUS_DEPOSIT_IN: "Нарахування бонусу",
      CASH_IN_BONUS: "Відіграний бонус",
      TOURNAMENT_PRIZE: "Нагорода за турнір",
      TOURNAMENT_PRIZE_MANUAL: "Нагорода за турнір",
      LOTTERY_PRIZE_MANUAL: "Нагорода за розіграш",
      ACCRUAL_BUY_BONUS: "Купівля бонусу"
    },
    transactionStates: {
      FINAL: "Поповнення",
      FINAL_OUT: "Виплачений",
      VALIDATION: "Перевірка",
      PROCESSING: "В обробці",
      PROCESSING_ERROR: "Помилка",
      APPROVE: "Підтверджено",
      REJECT: "Відхилено",
      MANUAL_REJECT: "Відмінено",
      NEW: "Очікує оплату"
    },
    bonusBalance: "На бонусному рахунку",
    newCard: "Нова картка",
    newCardDescription: "Номер картки вводиться при підтвердженні платежу на наступному кроці",
    previouslyUsedCards: "Раніше використовувані картки",
    availableCards: "Доступні картки",
    availableBonuses: "Доступні бонуси",
    withoutBonus: "Без бонуса",
    getBonus: "Забрати бонус",
    useBonus: "Оберіть свій бонус",
    bonusesAvailableCount: "Доступно бонусів",
    willBeYourTransactionHistory: "Тут буде історія твоїх транзакцій",
    newCardNotVerified: "Нова карта не верифікована",
    verifyYourCard: "Верифікуй карту",
    uploadOrMakeSelfieWithCard: "Завантажте або зробіть селфі з карткою для верифікації картки.",
    selfieWithCard: "Селфі з банківською карткою",
    makePay: "Поповнити баланс",
    minSumForBonus: "Упс... мінімальна сума поповнення для отримання бонусу {sum} {currency}. Продовжити поповнення без бонусу?",
    changeSum: "Змінити суму",
    anotherCard: "Інша карта",
    verifyCard: "Щоб оформити вивід коштів на вказану картку її необхідно верифікувати"
  },
  profile: {
    additionally: "Додатково",
    deleteAccount: "Видалити акаунт",
    deleteDefinitively: "Видалити акаунт без можливості його відновлення.",
    deleteConfirmation: "Ви впевнені, що хочете видалити цей акаунт?",
    removalAgreement: "Я ознайомлений з умовами видалення акаунта",
    accountDeleted: "Акаунт видалено",
    accountDeletedDescription: "Ваш акаунт успішно видалено",
    nickNameLengthRules: "Макимальна довжина 20 символів",
    copiedToBuffer: "ID Cкопійовано в буфер обміну",
    nickName: "Нікнейм",
    documents: "Документи",
    document: "Документ",
    profile: "Профіль",
    verification: "Верифікація",
    startVerification: "Приступити",
    myData: "Мої дані",
    secondName: "Прізвище",
    name: "Ім'я",
    fathersName: "По батькові",
    birthday: "Дата народження",
    male: "Чол.",
    female: "Жін.",
    city: "Місто",
    confirm: "Підтвердити",
    upload: "Завантажити",
    youAreNotVerified: "Ви не верифіковані",
    youAreVerified: "Ви верифіковані",
    needForVerification: "Перед здійсненням ставок та виводів вам необхідно верифікуватись",
    personalInformation: "Завантажуючи документ, ви погоджуєтеся на обробку персональних даних",
    pdfDetailDocument: "PDF з детальною інформацією.",
    chatInform: "Якщо у Вас виникли запитання - зверніться до чату підтримки. Наші оператори допоможуть вирішити питання.",
    maxDuration: "Максимальна тривалість верифікації – 72 години з моменту завантаження документів.",
    documentApproveAge: "Документ що засвідчує вашу особу та вік",
    documentPhoto: "Фото документу",
    documentList:
      "Паспорт (перший розворот), ID карта, водійське посвідчення та інші документи, що засвідчують вашу особу та вік (від 21 року)",
    passport: "Паспорт 1-2 ст. або ID-card лицьова",
    passport_back: "Паспорт 3-4 ст. або ID-card зворотня",
    documentTypePassport: "Паспорт",
    selfie: "Селфі",
    inn: "Ідентифікаційний номер платника податків",
    selfy: "Селфі з документом підтверджуючим вік",
    selfieWithDocument: "Селфі з документом",
    ageConfirm: "Документ підтверджуючий вік",
    ageConfirmBack: "Зворот документа підтверджуючий вік",
    acceptedToVerify: "Прийнято до перевірки",
    documentConfirmed: "Документ підтверджений",
    documentRejected: "Документ не прийнятий, завантажте повторно",
    documentRejectedShort: " не прийнятий, завантажте повторно",
    message: "Повідомлення",
    verifyEmail: "Підтвердіть ваш email",
    verifyPhoneNumber: "Підтвердіть ваш телефон",
    verifyPhoneModal: "Підтвердіть номер телефону",
    verifyPhoneAboutCode: "Введіть 6-значний код, який прийде у смс на номер",
    verifyPhoneCodeError: "Введіть 6-значний код",
    sendCodeAgain: "Надіслати код до СМС повторно",
    personalData: "Особисті дані",
    settings: "Налаштування",
    oldPassword: "Старий пароль",
    newPassword: "Новий пароль",
    typeNewPassword: "Вкажіть новий пароль",
    repeatNewPassword: "Повторити пароль",
    changePassword: "Зміна пароля",
    mailVerificationMessage: "Перейдіть на свою електронну пошту щоб закінчити процедуру підтвердження",
    writeOldPassword: "Введіть старий пароль",
    writeNewPassword: "Введіть новий пароль",
    writeRepeatPassword: "Повторіть новий пароль",
    passwordsMustBeIdentical: "Паролі не співпадають",
    mailSuccessTitle: "Успіх",
    mailSuccessDescription: "Ваша електронна пошта підтверджена",
    modalCapture: "Код з смс",
    dontReceiveCode: "Не отримали код?",
    tryAgain: "спробувати ще раз.",
    phoneSuccess: "Телефон підтверджений",
    passChangeSuccess: "Пароль успішно змінений",
    repeat: "Повторити",
    verificationTime: "Перевірка займає від 10 хвилин до кількох годин.",
    loadFile: "Завантажити файл",
    loadDocument: "Завантажити документ",
    addDocument: "Додати документ",
    loadSelfieWithDocument: "Додати селфі з документом",
    loadSelfieWithCard: "Додати селфі з карткою",
    selfieWithCardRequirements:
      "Ви можете надати виписку з банку, де буде видно номер картки та Ваше ПІБ, або Ви можете зробити скріншот реквізитів Вашої картки, де буде видно ці дані.",
    upLoad: "Завантажити",
    uploadStatus: "Статус завантажаення",
    verificationStatus: "Статус верифікації",
    wrongPassword: "Невірний пароль",
    imageRequirements:
      "Зображення, які ви надсилаєте, повинні бути хорошої якості, обличчя на них мають бути чіткі, а текст – легко читатися.",
    loadRules: "Правила завантаження",
    loadDocumentRules: "Правила завантаження документів",
    necessaryForVerification: "Для проходження верифікації, Вам потрібно:",
    successVerified: "Верифіковано",
    documentState: {
      verified: "Прийнято",
      rejected: "Відхилено",
      new: "Перевірка",
      rejectReason: "Причина відхилення",
      whyReject: "Чому я бачу статус Відхилено?",
      rejectExplanation: "Зображення, яке ви завантажили, не відповідає Правилам завантаження документів."
    },
    documentType: {
      passport: "Документ",
      selfy: "Селфі з документом",
      card: "Селфі з банківською карткою"
    },
    numberAlreadyExist: "Користувач с таким номером вже існує."
  },
  profileErrors: {
    nickname_already_exists_exception: "Такий нікнейм вже існує",
    something_went_wrong: "Щось пішло не так",
    account_belongs_to_another_user: "Цей акаунт вже закріплений за іншим користувачем"
  },
  payInErrors: {
    something_went_wrong: "Помилка поповнення",
    bonus_not_found_exception: "",
    user_already_has_active_bonus_exception: "У Вас вже є активний бонус",
    user_bonus_not_available_exception: "Шкода, але цей бонус недоступний зараз. Оберіть інший бонус із списку доступних"
  },
  header: {
    games: "Ігри",
    bonuses: "Бонуси",
    tournaments: "Турніри",
    promotions: "Акції",
    topUpAccount: "Поповнити рахунок"
  },
  navigation: {
    games: "Ігри",
    bonuses: "Бонуси",
    tournaments: "Турніри",
    promotions: "Акції",
    rules: "Правила",
    privacy: "Політика конфіденційності",
    offer: "Договір оферти",
    responsible: "Відповідальна гра",
    aboutus: "Про нас",
    license: "Ліцензія",
    support: "Підтримка",
    home: "Головна",
    documents: "Документи",
    profile: "Профіль",
    balance: "Баланс",
    lotteries: "Розіграші",
    settings: "Налаштування",
    jackpots: "Джекпоти",
    jackpot: "JACKPOT",
    mega: "MEGA",
    big: "BIG",
    treasures: "Скарби дракона",
    "royal-club": "ROYAL CLUB",
    uaPolicyAML: "Відмивання грошей",
    policyAML: "Policy AML",
    pages: "Новинки",
    nominations: "Ліга дракона",
    responsibleGaming: "Відповідальна гра",
    refundPolicy: "Політика повернення коштів",
    pwa: "Додаток"
  },
  jackpot: {
    chooseGame: "Обрати гру",
    takePartAllGames: "БЕРУТЬ УЧАСТЬ ВСI IГРИ",
    winners: "НАШІ ПЕРЕМОЖЦІ",
    player: "Гравець",
    win: "Виграв",
    game: "Гра",
    tableBet: "Ставка",
    loadMore: "Завантажити ще"
  },
  questionnaire: {
    wantPersonalBonus: "Хочете отримувати персональні для Вас бонуси?",
    telUsAbout:
      "Розкажіть які ігри, вейджер та номінали Вам подобаються. Це допоможе нам в майбутньому давати більше персональних пропозицій для Вас.",
    noBonuses: "Не хочу персональні бонуси",
    next: "Далі",
    bonusType: "Який вид бонуса Вам більше подобаєтся?",
    wager: "Який вейджер Ви вважаєте реальним при активації бонусу?",
    wagerAnnotation: "Але чим менше вейджер, тим менше бонус",
    choseBtnMulti: "Оберіть 1 або декілька варіантів",
    choseBtn: "Оберіть 1 варінт",
    further: "Далі",
    thanks: "Дякуємо!",
    hugePrice: "Почніть отримувати великі виграші вже зараз, поки ми підбираємо цікаві пропозиції для Вас.",
    addition: "Поповнення",
    newBonusPlayer: "Бонус нового гравця"
  },
  myAchievements: {
    title: "Мої досягнення",
    all: "Всі",
    choseCoin: "Обирай елемент для відіграшу",
    checkAchievements: "Перевіряй свої досягнення",
    noBonuses: "Ой… Бонусів поки немає",
    receiveBonuses: "Отримуй сповіщення про нові бонуси",
    youBot: "ТВІЙ бот | ПОМІЧНИК",
    goToTg: "Залітай за щоденними бонусами",
    justOneCoinPlay: "Елемент який відігруєте зараз",
    topGames: "ТОП Улюблених ігр",
    maxWin: "виграш",
    royal: "Залітай в клуб для обранних",
    royalDesk: "Роби депозити і отримуй круті бонуси Royal Club",
    dragonsTreasure: "Cкарби дракона",
    lotOfBonuses: "Безмежна кількість бонусів",
    controlTreasures: "Контролюй добування скарбів",
    chestCollected: "Сундук зібрано"
  },
  nominations: {
    title: "ЗУСТРІЧАЙТЕ! Золота Ліга Дракона",
    finishedTitle: "Фіналісти Дракоін року 2022",
    description:
      "Ми знаємо, що всі чекають на підсумки року! Тому ми презентуємо номінації на кращих гравців 2022 року! Ми розробили 23 унікальних номінації, за які зможуть поборотись найкращі серед кращих! Проте, переможець в кожній номінації може бути лише один. А хто ним стане, покаже - ЗМАГАННЯ РОКУ! Кожен переможець отримає ПЕРСОНАЛЬНІ ПОДАРУНКИ та УНІКАЛЬНІ ПОЗНАЧКИ В ПРОФІЛІ, яких не буде більше ні в кого! А найголовніше, стане учасником Ліги Дракона, і отримає право на унікальні пропозиції від казино Dragon`s Gold.",
    rulesTitle: "Хто вони, майбутні переможці?",
    rulesDescription:
      "В кожній номінації ми маємо список претендентів, в залежності від виконання необхідного критерію, по кожній з них. Список не фіналізовано, і він може змінюватися протягом поточного місяця, тому шанси на перемогу має кожен активний гравець. Переможці і нагороди будуть озвучені 30 грудня. Кожен гравець, що виграє в номінації, отримає унікальний золотий орден в своєму профілі, і зможе відображати його біля свого ніку на сайті. Номінанти зможуть перевірити інформацію про участь у змаганні в розділі сайту 'Мої досягнення'. УВАГА: Щоб перемогти, потрібно збільшити активність в своїй номінації у цьому місяці!",
    achievements: "Досягнення",
    chooseAchievement: "Обирай нагороду яку побачать усі",
    pretendDescription:
      "Ви стали претендентом на виграш в наступних номінаціях! Кожна номінація дає унікальні звання і можливість отримувати незвичайні пропозиції.",
    allWinners: "Всі переможці",
    additional: "Інші нагороди"
  },
  transactionFailed: {
    ups: "Упс.. Вивід не пройшов!",
    upsLong: "Вивід не пройшов по технічним причинам на стороні платіжної системи.",
    howMuch: "На Ваш рахунок повернулось",
    repeatPeyOut: "ПОВТОРИТИ ВИВІД"
  },
  notFoundPage: {
    pageNotFound: "Вибачте,<br>сторінка не знайдена",
    pageNotFoundSubText: "Можливо ця сторінка була вилучена,<br>або допущена помилка в адресі.",
    pageNotFoundSecondSubText: "Ви можете скористатися головним меню<br>або перейти на головну.",
    youCan: "Ви можете перевірити:",
    or: "або перейти"
  },
  pwaPage: {
    desktopApp: "DESKTOP ДОДАТОК",
    iosApp: "IOS ДОДАТОК",
    androidApp: "ANDROID PWA ДОДАТОК",
    desktopSubText: "Скачуй додаток Dragon`s Gold Україна - та залітай за виграшом ще швидше.",
    iosSubText: "5 кроків для швидкого встановлення додатку.",
    androidSubText: "Скачуй додаток Dragon`s Gold  - залишайся з драконом будь де, будь коли!",
    desktopFirstStep: "1. Відкрийте в браузері сайт dragongold88.com та натиснути кнопку встановити в адресній строці.",
    desktopSecondStep: "2 Встановіть додаток на робочий стіл.",
    desktopThirdStep: "3. Насолоджуйтесь швидким доступом через додаток.",
    iosFirstStep: "1. Відкрити у браузер Safari сайт dragongold88.com",
    iosSecondStep: "2. Відкрити розділ поділитись",
    iosThirdStep: "3. Оберіть пункт - На екран додому",
    iosFourthStep: "4. Оберіть пункт - Додати",
    iosFivesStep: "5. Насолоджуйтесь швидким доступом",
    instruction: "ІНСТРУКЦІЯ",
    collapse: "Згорнути",
    download: "ВСТАНОВИТИ PWA",
    advantagesTitle: "Переваги програми Dragon`s Gold:",
    advantageOne: "миттєве виведення коштів;",
    advantageTwo: "регулярні бонуси та акції;",
    advantageThree: "зручний інтерфейс;",
    app: "ДОДАТОК"
  }
};
export default messages;
